name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install Dependencies
        run: yarn install
      
      - name: Run Linter
        run: yarn lint

      - name: Run Test Suite
        run: yarn test:ci
